import { db } from './firebase.node'

const samplePlaces = [
  // Popular Cafes & Restaurants
  {
    placeId: 'cafe-indiranagar-1',
    title: 'Third Wave Coffee Roasters',
    description: 'Specialty coffee with single-origin beans, artisanal brewing methods, and cozy ambiance perfect for work or meetings.',
    category: 'food_cafe',
    subcategory: 'cafe',
    tags: ['coffee', 'wifi', 'work-friendly', 'specialty-coffee', 'brunch'],
    cuisine: ['Coffee', 'Continental'],
    location: { lat: 12.9784, lng: 77.6408 },
    address: '100 Feet Road, Indiranagar',
    city: 'Bengaluru',
    neighbourhood: 'Indiranagar',
    images: [],
    avgRating: 4.6,
    reactionCount: { like: 156, love: 89, save: 134 },
    foodPriceRange: '₹₹',
    timings: '8:00 AM - 11:00 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 2145, featuredScore: 453 },
  },
  {
    placeId: 'restaurant-koramangala-1',
    title: 'Truffles',
    description: 'Iconic burger joint famous for massive burgers, shakes, and American comfort food. Always packed with crowds!',
    category: 'food_cafe',
    subcategory: 'restaurant',
    tags: ['burgers', 'american', 'casual-dining', 'popular', 'shakes'],
    cuisine: ['American', 'Fast Food'],
    location: { lat: 12.9352, lng: 77.6245 },
    address: 'St. Marks Road, Koramangala',
    city: 'Bengaluru',
    neighbourhood: 'Koramangala',
    images: [],
    avgRating: 4.5,
    reactionCount: { like: 234, love: 167, save: 198 },
    foodPriceRange: '₹₹',
    timings: '12:00 PM - 11:30 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 3456, featuredScore: 678 },
  },
  {
    placeId: 'cafe-hsr-1',
    title: 'Brahmin\'s Coffee Bar',
    description: 'Legendary South Indian breakfast spot serving authentic filter coffee, idlis, and vadas since 1965.',
    category: 'food_cafe',
    subcategory: 'cafe',
    tags: ['south-indian', 'breakfast', 'filter-coffee', 'iconic', 'budget-friendly'],
    cuisine: ['South Indian'],
    location: { lat: 12.9121, lng: 77.6446 },
    address: 'Basavanagudi, Gandhi Bazaar',
    city: 'Bengaluru',
    neighbourhood: 'Basavanagudi',
    images: [],
    avgRating: 4.7,
    reactionCount: { like: 312, love: 245, save: 278 },
    foodPriceRange: '₹',
    timings: '6:30 AM - 11:00 AM, 3:30 PM - 8:30 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 4123, featuredScore: 823 },
  },
  {
    placeId: 'restaurant-mg-road-1',
    title: 'Toit Brewpub',
    description: 'Popular microbrewery with craft beers, wood-fired pizzas, and lively atmosphere. Great for groups!',
    category: 'food_cafe',
    subcategory: 'restaurant',
    tags: ['brewery', 'craft-beer', 'pizza', 'nightlife', 'live-music'],
    cuisine: ['Continental', 'Italian'],
    location: { lat: 12.9756, lng: 77.6068 },
    address: 'Indiranagar',
    city: 'Bengaluru',
    neighbourhood: 'Indiranagar',
    images: [],
    avgRating: 4.4,
    reactionCount: { like: 445, love: 298, save: 367 },
    foodPriceRange: '₹₹₹',
    timings: '12:00 PM - 11:30 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 5234, featuredScore: 1023 },
  },
  {
    placeId: 'cafe-whitefield-1',
    title: 'Blue Tokai Coffee Roasters',
    description: 'Premium coffee experience with pour-overs, cold brews, and freshly baked goods in a modern setting.',
    category: 'food_cafe',
    subcategory: 'cafe',
    tags: ['specialty-coffee', 'pour-over', 'modern', 'work-friendly', 'pastries'],
    cuisine: ['Coffee', 'Bakery'],
    location: { lat: 12.9698, lng: 77.7499 },
    address: 'Whitefield Main Road',
    city: 'Bengaluru',
    neighbourhood: 'Whitefield',
    images: [],
    avgRating: 4.6,
    reactionCount: { like: 189, love: 123, save: 156 },
    foodPriceRange: '₹₹',
    timings: '8:00 AM - 10:00 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 2567, featuredScore: 512 },
  },
  
  // Activities & Entertainment
  {
    placeId: 'activity-koramangala-2',
    title: 'Smaaash',
    description: 'Ultimate entertainment center with VR games, cricket simulators, go-karting, and arcade games.',
    category: 'activities',
    activityType: 'gaming',
    tags: ['gaming', 'vr', 'arcade', 'cricket', 'go-karting', 'family-friendly'],
    location: { lat: 12.9279, lng: 77.6271 },
    address: 'Koramangala 7th Block',
    city: 'Bengaluru',
    neighbourhood: 'Koramangala',
    images: [],
    avgRating: 4.3,
    reactionCount: { like: 267, love: 145, save: 223 },
    activityPriceRange: '₹₹₹',
    activityDuration: 120,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 3245, featuredScore: 645 },
  },
  {
    placeId: 'activity-hsr-2',
    title: 'Climb Central',
    description: 'Premier indoor bouldering and rock climbing gym with routes for beginners to experts.',
    category: 'activities',
    activityType: 'sports',
    tags: ['climbing', 'fitness', 'bouldering', 'training', 'adventure'],
    location: { lat: 12.9089, lng: 77.6388 },
    address: 'HSR Layout Sector 2',
    city: 'Bengaluru',
    neighbourhood: 'HSR Layout',
    images: [],
    avgRating: 4.7,
    reactionCount: { like: 178, love: 134, save: 167 },
    activityPriceRange: '₹₹',
    activityDuration: 90,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 2134, featuredScore: 456 },
  },
  {
    placeId: 'activity-malleshwaram-1',
    title: 'Rangashankara Theatre',
    description: 'Renowned theatre space showcasing plays, dramas, and cultural performances in multiple languages.',
    category: 'activities',
    activityType: 'cultural',
    tags: ['theatre', 'drama', 'cultural', 'arts', 'performances'],
    location: { lat: 12.9964, lng: 77.5704 },
    address: 'JP Nagar',
    city: 'Bengaluru',
    neighbourhood: 'JP Nagar',
    images: [],
    avgRating: 4.8,
    reactionCount: { like: 234, love: 189, save: 212 },
    activityPriceRange: '₹₹',
    activityDuration: 150,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 2890, featuredScore: 578 },
  },
  {
    placeId: 'activity-ulsoor-1',
    title: 'Ulsoor Lake',
    description: 'Serene lake perfect for morning walks, boating, and picnics. Beautiful sunset views!',
    category: 'activities',
    activityType: 'outdoors',
    tags: ['lake', 'boating', 'nature', 'picnic', 'sunset', 'walking'],
    location: { lat: 12.9810, lng: 77.6180 },
    address: 'Ulsoor',
    city: 'Bengaluru',
    neighbourhood: 'Ulsoor',
    images: [],
    avgRating: 4.2,
    reactionCount: { like: 312, love: 234, save: 289 },
    activityPriceRange: '₹',
    activityDuration: 60,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 4567, featuredScore: 890 },
  },
  {
    placeId: 'activity-jayanagar-1',
    title: 'Lalbagh Botanical Garden',
    description: 'Historic 240-acre garden with diverse flora, glass house, and peaceful walking trails.',
    category: 'activities',
    activityType: 'outdoors',
    tags: ['garden', 'nature', 'photography', 'walking', 'historical', 'peaceful'],
    location: { lat: 12.9507, lng: 77.5848 },
    address: 'Mavalli, Lalbagh',
    city: 'Bengaluru',
    neighbourhood: 'Lalbagh',
    images: [],
    avgRating: 4.6,
    reactionCount: { like: 456, love: 378, save: 423 },
    activityPriceRange: '₹',
    activityDuration: 120,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 6234, featuredScore: 1245 },
  },
  
  // Movies & Cinema
  {
    placeId: 'movie-koramangala-1',
    title: 'PVR Koramangala',
    description: 'Premium multiplex with IMAX, 4DX, and Gold Class lounges. Latest blockbusters and comfort.',
    category: 'movies',
    tags: ['multiplex', 'imax', '4dx', 'premium', 'gold-class'],
    location: { lat: 12.9345, lng: 77.6101 },
    address: 'Forum Mall, Koramangala',
    city: 'Bengaluru',
    neighbourhood: 'Koramangala',
    images: [],
    avgRating: 4.5,
    reactionCount: { like: 389, love: 267, save: 334 },
    releaseDate: null,
    genre: ['Action', 'Drama', 'Comedy'],
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 4890, featuredScore: 978 },
  },
  {
    placeId: 'movie-whitefield-2',
    title: 'INOX Whitefield',
    description: 'Modern cinema with Dolby Atmos sound, laser projection, and luxury recliner seats.',
    category: 'movies',
    tags: ['multiplex', 'dolby-atmos', 'recliner', 'modern', 'valet-parking'],
    location: { lat: 12.9692, lng: 77.7501 },
    address: 'Phoenix Marketcity, Whitefield',
    city: 'Bengaluru',
    neighbourhood: 'Whitefield',
    images: [],
    avgRating: 4.4,
    reactionCount: { like: 312, love: 223, save: 278 },
    releaseDate: null,
    genre: ['Hollywood', 'Bollywood', 'Regional'],
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 3890, featuredScore: 778 },
  },
  {
    placeId: 'movie-jayanagar-1',
    title: 'Gopalan Cinemas',
    description: 'Affordable multiplex with multiple screens showing latest releases. Great food court options.',
    category: 'movies',
    tags: ['multiplex', 'affordable', 'family-friendly', 'food-court'],
    location: { lat: 12.9281, lng: 77.5838 },
    address: 'Jayanagar 3rd Block',
    city: 'Bengaluru',
    neighbourhood: 'Jayanagar',
    images: [],
    avgRating: 4.2,
    reactionCount: { like: 267, love: 189, save: 223 },
    releaseDate: null,
    genre: ['Kannada', 'Hindi', 'English'],
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 3234, featuredScore: 645 },
  },
  
  // More unique places
  {
    placeId: 'cafe-church-street-1',
    title: 'Koshy\'s',
    description: 'Legendary 1940s Irani cafe with vintage charm, serving continental and Indian cuisine.',
    category: 'food_cafe',
    subcategory: 'cafe',
    tags: ['iconic', 'vintage', 'continental', 'heritage', 'breakfast'],
    cuisine: ['Continental', 'Indian'],
    location: { lat: 12.9766, lng: 77.6033 },
    address: 'St. Marks Road',
    city: 'Bengaluru',
    neighbourhood: 'Church Street',
    images: [],
    avgRating: 4.3,
    reactionCount: { like: 398, love: 312, save: 356 },
    foodPriceRange: '₹₹',
    timings: '8:30 AM - 11:00 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 4567, featuredScore: 912 },
  },
  {
    placeId: 'activity-cubbon-park-1',
    title: 'Cubbon Park',
    description: 'Massive 300-acre central park perfect for jogging, cycling, yoga, and nature walks.',
    category: 'activities',
    activityType: 'outdoors',
    tags: ['park', 'jogging', 'cycling', 'yoga', 'nature', 'morning-walk'],
    location: { lat: 12.9762, lng: 77.5929 },
    address: 'Kasturba Road',
    city: 'Bengaluru',
    neighbourhood: 'Cubbon Park',
    images: [],
    avgRating: 4.7,
    reactionCount: { like: 523, love: 445, save: 489 },
    activityPriceRange: 'Free',
    activityDuration: 90,
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 7890, featuredScore: 1578 },
  },
  {
    placeId: 'restaurant-residency-road-1',
    title: 'MTR (Mavalli Tiffin Rooms)',
    description: 'Iconic 95-year-old restaurant serving authentic Karnataka meals and breakfast items.',
    category: 'food_cafe',
    subcategory: 'restaurant',
    tags: ['south-indian', 'heritage', 'iconic', 'breakfast', 'thali'],
    cuisine: ['South Indian', 'Karnataka'],
    location: { lat: 12.9543, lng: 77.5849 },
    address: 'Lalbagh Road, Mavalli',
    city: 'Bengaluru',
    neighbourhood: 'Mavalli',
    images: [],
    avgRating: 4.6,
    reactionCount: { like: 567, love: 478, save: 523 },
    foodPriceRange: '₹₹',
    timings: '6:30 AM - 11:00 AM, 12:30 PM - 3:30 PM, 7:00 PM - 9:00 PM',
    createdBy: 'seed',
    contributors: [],
    status: 'published',
    meta: { views: 8234, featuredScore: 1645 },
  },
]

async function main() {
  console.log('🌱 Starting to seed places...')

  for (const p of samplePlaces) {
    const ref = db.collection('places').doc(p.placeId)
    await ref.set({
      ...p,
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    console.log('✅ Seeded:', p.title)
  }
}

main().then(
  () => {
    console.log('\n🎉 Seeding complete! Added', samplePlaces.length, 'places to Firebase')
    console.log('📍 All places are in Bangalore with real coordinates')
    process.exit(0)
  },
  (err) => {
    console.error('❌ Seeding failed:', err)
    process.exit(1)
  },
)
